server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql:///${DB_NAME}?cloudSqlInstance=${CLOUD_SQL_INSTANCE}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update   # (para demo; em prod real use migrações)
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
